services:
  catalog.api:
    container_name: catalog.api
    build:
      context: .
      dockerfile: Catalog.API.Web/Dockerfile
    pull_policy: build      
    restart: unless-stopped

  catalog.auth:
    container_name: catalog.auth
    build:
      context: .
      dockerfile: Catalog.Auth/Dockerfile
    pull_policy: build
    restart: unless-stopped

  envoygateway:
    container_name: envoygateway
    image: envoyproxy/envoy-distroless:v1.32.2
    depends_on:
      - catalog.api
      - catalog.auth
    pull_policy: missing
    restart: unless-stopped
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./Envoy/envoy.crt:/etc/ssl/certs/envoy.crt
      - ./Envoy/envoy_key.pem:/etc/ssl/certs/envoy_key.pem