// <auto-generated />
using Catalog.Auth.Infrastructure;
using Microsoft.EntityFrameworkCore.Infrastructure;
using MyCompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AuthDbContext), typeof(AuthDbContextModel))]
