// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Catalog.API.Infrastructure.Persistence.CompiledModels
{
    public partial class CatalogContextModel
    {
        private CatalogContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("852a822e-0bea-4a47-9633-3aa44a8dccf1"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var brand = BrandEntityType.Create(this);
            var product = ProductEntityType.Create(this);

            ProductEntityType.CreateForeignKey1(product, brand);

            BrandEntityType.CreateAnnotations(brand);
            ProductEntityType.CreateAnnotations(product);

            AddAnnotation("ProductVersion", "10.0.1");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
