// <auto-generated />
using Catalog.API.Infrastructure.Persistence;
using Catalog.API.Infrastructure.Persistence.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(CatalogContext), typeof(CatalogContextModel))]
